spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=QuanAnNgocTuyet;encrypt=false;
spring.datasource.username=${DB_USERNAME:sa}
spring.datasource.password=${DB_PASSWORD:THGaming809}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.show-sql=false

# Cấu hình Hibernate
spring.jpa.hibernate.ddl-auto=update

# Cấu hình thời gian đăng nhập (24 giờ)
server.servlet.session.timeout=24h
server.servlet.session.cookie.max-age=2592000
server.servlet.session.cookie.same-site=lax

